<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Volume_select_Ignore1</name>
   <tag></tag>
   <elementGuidId>d2165dbf-1a59-4b92-8024-3307e21c5cbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;volume&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='volume']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>918d080f-0689-4ab9-8bf9-aecf3a2d014e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control volSel</value>
      <webElementGuid>961c3b53-1052-44fb-bb26-66af2324a506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>volume</value>
      <webElementGuid>683adce8-09f2-46c7-bb0a-f0a229015119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Volume #</value>
      <webElementGuid>2f7866f7-d85e-4cce-8d16-996a5a0b1172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ignore#1</value>
      <webElementGuid>ac47aefb-29aa-42d2-8ac4-bf2a7d5d343b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;volume-cmr&quot;)/div[@class=&quot;col-md-3&quot;]/select[@class=&quot;form-control volSel&quot;]</value>
      <webElementGuid>844cb122-b394-42a3-a5ae-afff6b929993</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='volume']</value>
      <webElementGuid>1999ae2e-a5ab-4095-855e-2de44a5d7a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='volume-cmr']/div/select</value>
      <webElementGuid>6f76de5a-0ee1-4d53-8fd3-79034171c100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volume'])[1]/following::select[1]</value>
      <webElementGuid>5cbe4239-03e4-4a74-9acc-9b2f7940f5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='% Upside variance'])[1]/preceding::select[1]</value>
      <webElementGuid>f4e3bf62-f343-48bd-a6c6-3f00a1c437fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use Wildcards'])[1]/preceding::select[2]</value>
      <webElementGuid>51878b21-208a-4dd7-95af-91f01be2f068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>c14cbab8-7919-4cc8-8967-d04ddd23c2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'volume' and @placeholder = 'Select Volume #' and (text() = 'Ignore#1' or . = 'Ignore#1')]</value>
      <webElementGuid>fa42483d-10e8-4bf7-b072-72093bd3ebcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
